### ISSUE TITLE
One more bug report

### ISSUE THREAD

**Issue by micron10** [dpdk-vbng-cp/accel-ppp#41]
Hi Team

after receive this package service killed:

[2022-09-26 16:43:30.091] vlan435: recv [PPPoE PADI 10:62:eb:19:32:2e => ff:ff:ff:ff:ff:ff sid=0000 <Service-Name periodic> <Host-Uniq 707070326531>]
[2022-09-26 16:43:30.091] vlan435: send [PPPoE PADO ac:1f:6b:a4:0b:6a => 10:62:eb:19:32:2e sid=0000 <AC-Name PERIODIC> <Service-Name periodic> <AC-Cookie 5c65b01f167c34ebf740a1cc0ca5dfcc071a7f7f65782e91> <Host-Uniq 707070326531>]
[2022-09-26 16:43:30.108] vlan435: recv [PPPoE PADR 10:62:eb:19:32:2e => ac:1f:6b:a4:0b:6a sid=0000 <Unknown (1101)> <AC-Cookie 5c65b01f167c34ebf740a1cc0ca5dfcc071a7f7f65782e91>]

block user mac on switch and nnot have time to run gdb to get log .

I will try to allow and get log from gdb

**Comment by micron10** [comment]
Here is update with debug log : 

Thread 32 "accel-ppp" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 1638220]
allocate_channel (ppp_max_payload=0, cookie=<optimized out>, tr101=0x0, service_name=<optimized out>, relay_sid=0x0, host_uniq=0x7fffec002530, addr=0x7fffec002502 "\260\247\271z\035\210\210c\021\031", serv=0x466a80)                                                                    at /build/accel-ppp-master/accel-pppd/ctrl/pppoe/pppoe.c:349             349     /build/accel-ppp-master/accel-pppd/ctrl/pppoe/pppoe.c: No such file or directory.
(gdb)
(gdb)
(gdb) bt full
#0  allocate_channel (ppp_max_payload=0, cookie=<optimized out>, tr101=0x0,
    service_name=<optimized out>, relay_sid=0x0, host_uniq=0x7fffec002530,
    addr=0x7fffec002502 "\260\247\271z\035\210\210c\021\031", serv=0x466a80)
    at /build/accel-ppp-master/accel-pppd/ctrl/pppoe/pppoe.c:349
    conn = 0x7fffd8049b78
    old_sid_ptr = <optimized out>
    subscriber_tags = <optimized out>
    conn = <optimized out>
    old_sid_ptr = <optimized out>
    subscriber_tags = <optimized out>
    bit = <optimized out>
	#1  pppoe_recv_PADR (size=<optimized out>,
    pack=0x7fffec0024fc "<\354\357\267\332x\260\247\271z\035\210\210c\021\031",
    serv=0x466a80)
    at /build/accel-ppp-master/accel-pppd/ctrl/pppoe/pppoe.c:1301
    service_name_tag = <optimized out>
    service_match = <optimized out>
    conn = <optimized out>
    vendor_id = <optimized out>
    ethhdr = 0x7fffec0024fc
    hdr = 0x7fffec00250a
    tag = <optimized out>
    host_uniq_tag = 0x7fffec002530
    ac_cookie_tag = <optimized out>
    tr101_tag = 0x0
    n = <optimized out>
    ppp_max_payload = 0
    relay_sid_tag = 0x0
    ethhdr = <optimized out>
    hdr = <optimized out>
    tag = <optimized out>
    host_uniq_tag = <optimized out>
    relay_sid_tag = <optimized out>
    ac_cookie_tag = <optimized out>
    service_name_tag = <optimized out>
    tr101_tag = <optimized out>
    n = <optimized out>
    service_match = <optimized out>
    conn = <optimized out>
    vendor_id = <optimized out>
    ppp_max_payload = <optimized out>
    svc_index = <optimized out>
	#2  pppoe_serv_read (data=0x7fffec0024f8 "@")
    at /build/accel-ppp-master/accel-pppd/ctrl/pppoe/pppoe.c:1350
    serv = 0x466a80
    pack = 0x7fffec0024fc "<\354\357\267\332x\260\247\271z\035\210\210c\021\031"
    hdr = 0x7fffec00250a
    n = <optimized out>
	#3  0x00007ffff782fd83 in ctx_thread (ctx=<optimized out>)
    at /build/accel-ppp-master/accel-pppd/triton/triton.c:294
    call = 0x7fffec0044d8
    tt = 1
    h = <optimized out>
    t = <optimized out>
    events = <optimized out>
    h = <optimized out>
    t = <optimized out>
    call = <optimized out>
    tt = <optimized out>
    events = <optimized out>
	#4  triton_thread (thread=0x6352f0)
    at /build/accel-ppp-master/accel-pppd/triton/triton.c:209
    set = {__val = {516, 0 <repeats 15 times>}}
    sig = 10
    need_free = <optimized out>
    stack = 0x0
	#5  0x00007ffff76a2753 in ?? () from /lib64/libc.so.6
	No symbol table info available.
	#6  0x00007ffff772f35c in ?? () from /lib64/libc.so.6
	No symbol table info available.

**Comment by micron10** [comment]
(gdb) bt full
#0  allocate_channel (ppp_max_payload=0, cookie=<optimized out>, tr101=0x0,
    service_name=<optimized out>, relay_sid=0x0, host_uniq=0x7fffec002b8b,
    addr=0x7fffec002b72 "\274\017\232\351\303\223\210c\021\031", serv=0x7fffe4016b90)
    at /build/accel-ppp-master/accel-pppd/ctrl/pppoe/pppoe.c:349
        conn = 0x7fffcc18ead8
        old_sid_ptr = <optimized out>
        subscriber_tags = <optimized out>
        conn = <optimized out>
        old_sid_ptr = <optimized out>
        subscriber_tags = <optimized out>
        bit = <optimized out>
#1  pppoe_recv_PADR (size=<optimized out>,
    pack=0x7fffec002b6c "<\354\357\267\332x\274\017\232\351\303\223\210c\021\031",
    serv=0x7fffe4016b90)
    at /build/accel-ppp-master/accel-pppd/ctrl/pppoe/pppoe.c:1301
        service_name_tag = <optimized out>
        service_match = <optimized out>
        conn = <optimized out>
        vendor_id = <optimized out>
        ethhdr = 0x7fffec002b6c
        hdr = 0x7fffec002b7a
        tag = <optimized out>
        host_uniq_tag = 0x7fffec002b8b
        ac_cookie_tag = <optimized out>
        tr101_tag = 0x0
        n = <optimized out>
        ppp_max_payload = 0
        relay_sid_tag = 0x0
        ethhdr = <optimized out>
        hdr = <optimized out>
        tag = <optimized out>
        host_uniq_tag = <optimized out>
        relay_sid_tag = <optimized out>
        ac_cookie_tag = <optimized out>
        service_name_tag = <optimized out>
        tr101_tag = <optimized out>
        n = <optimized out>
        service_match = <optimized out>
        conn = <optimized out>
        vendor_id = <optimized out>
        ppp_max_payload = <optimized out>
        svc_index = <optimized out>
#2  pppoe_serv_read (data=0x7fffec002b68 "C")
    at /build/accel-ppp-master/accel-pppd/ctrl/pppoe/pppoe.c:1350
        serv = 0x7fffe4016b90
        pack = 0x7fffec002b6c "<\354\357\267\332x\274\017\232\351\303\223\210c\021\031"
        hdr = 0x7fffec002b7a
        n = <optimized out>
#3  0x00007ffff782fd83 in ctx_thread (ctx=<optimized out>)
    at /build/accel-ppp-master/accel-pppd/triton/triton.c:294
        call = 0x7fffc8015f18
        tt = 1
        h = <optimized out>
        t = <optimized out>
        events = <optimized out>
        h = <optimized out>
        t = <optimized out>
        call = <optimized out>
        tt = <optimized out>
        events = <optimized out>
#4  triton_thread (thread=0x632170)
    at /build/accel-ppp-master/accel-pppd/triton/triton.c:209
        set = {__val = {516, 0 <repeats 15 times>}}
        sig = 10
        need_free = <optimized out>
        stack = 0x0
#5  0x00007ffff76a2753 in ?? () from /lib64/libc.so.6
No symbol table info available.
#6  0x00007ffff772f35c in ?? () from /lib64/libc.so.6
No symbol table info available.

**Comment by micron10** [comment]
fix
